# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Princess Diaries
email: sun8wd@163.com
description: > # this means to ignore newlines until "baseurl:"
    This is just another Jekyll theme.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://auu.im" # the base hostname & protocol for your site
facebook: 
github:  https://github.com/sun8wd
twitter: 

# Build settings
markdown: kramdown

paginate: 3
paginate_path: "page:num"


gems: [jekyll-paginate] 
